In [1]:
#importing needed libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from google.colab import files
from imblearn.over_sampling import SMOTE
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import confusion_matrix, accuracy_score


In [3]:
uploaded = files.upload()

Saving Student Performance Prediction-Binary.csv to Student Performance Prediction-Binary.csv


In [ ]:
#!pip install -U imbalanced-learn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 226 kB 8.1 MB/s 
  Attempting uninstall: imbalanced-learn
    Found existing installation: imbalanced-learn 0.8.1
    Uninstalling imbalanced-learn-0.8.1:
      Successfully uninstalled imbalanced-learn-0.8.1


In [4]:
#uploading data
df = pd.read_csv('Student Performance Prediction-Binary.csv')

In [5]:
df

Student ID  Quiz01 [10]  Assignment01 [8]  Midterm Exam [20]  \
0    student000000           95                91                 70   
1    student000001           85                76                 65   
2    student000002           85                41                 73   
3    student000003           80                78                 80   
4    student000004           85                91                 78   
..             ...          ...               ...                ...   
481  student000481           90                85                 93   
482  student000482           80                68                 93   
483  student000483           80                86                 93   
484  student000484           75                68                 80   
485  student000485           85                81                 88   

     Assignment02 [12]  Assignment03 [25]  Final Exam [35]  Course Grade  \
0                   90                 84               64            85   
1                   61                 73               64            76   
2                   61                 73               61            73   
3                   79                 79               57            80   
4                   80                 84               67            85   
..                 ...                ...              ...           ...   
481                 87                 81               77            92   
482                 70                 83               83            90   
483                 95                 90               83            96   
484                 76                 88               50            78   
485                 86                 96               60            88   

     Total [100] Class  
0             85     G  
1             76     G  
2             73     G  
3             79     G  
4             85     G  
..           ...   ...  
481           92     G  
482           90     G  
483           96     G  
484           78     G  
485           88     G  

[486 rows x 10 columns]

In [6]:
df.drop(columns=['Student ID'],inplace=True)

In [7]:
df

Quiz01 [10]  Assignment01 [8]  Midterm Exam [20]  Assignment02 [12]  \
0             95                91                 70                 90   
1             85                76                 65                 61   
2             85                41                 73                 61   
3             80                78                 80                 79   
4             85                91                 78                 80   
..           ...               ...                ...                ...   
481           90                85                 93                 87   
482           80                68                 93                 70   
483           80                86                 93                 95   
484           75                68                 80                 76   
485           85                81                 88                 86   

     Assignment03 [25]  Final Exam [35]  Course Grade  Total [100] Class  
0                   84               64            85           85     G  
1                   73               64            76           76     G  
2                   73               61            73           73     G  
3                   79               57            80           79     G  
4                   84               67            85           85     G  
..                 ...              ...           ...          ...   ...  
481                 81               77            92           92     G  
482                 83               83            90           90     G  
483                 90               83            96           96     G  
484                 88               50            78           78     G  
485                 96               60            88           88     G  

[486 rows x 9 columns]

In [8]:
# X and Y at 20% of the data (quiz1,assignment1)
x_20 =df.iloc[:, 0:2].values
y_20= df.iloc[:, -1].values

In [9]:
x_20

array([[ 95,  91],
       [ 85,  76],
       [ 85,  41],
       [ 80,  78],
       [ 85,  91],
       [ 80,  79],
       [ 70,  91],
       [ 75,  65],
       [ 80,  87],
       [ 70,  68],
       [ 90,  93],
       [ 70,  93],
       [ 80,  86],
       [ 80,  86],
       [100,  92],
       [ 80,  80],
       [ 75,  86],
       [ 70,  70],
       [ 90,  58],
       [ 80,  64],
       [ 65,  93],
       [ 80,  76],
       [ 70,  79],
       [ 80,  67],
       [ 70,  85],
       [ 70,  67],
       [ 70,  85],
       [ 85,  82],
       [ 85,  78],
       [ 95,  68],
       [ 95,  89],
       [ 70,  79],
       [ 80,  86],
       [ 80,  73],
       [ 95,  90],
       [ 85,  83],
       [ 75,  88],
       [ 80,  92],
       [ 80,  96],
       [ 75,  90],
       [ 90,  93],
       [ 75,   0],
       [ 75,  85],
       [ 90,  78],
       [ 70,  82],
       [ 85,  80],
       [ 75,  83],
       [ 85,  77],
       [ 90,  85],
       [ 80,  86],
       [ 70,  84],
       [ 75,  84],
       [ 70,

In [10]:
y_20

array(['G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G',
       'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G',
       'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G',
       'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G',
       'G', 'G', 'G', 'G', 'G', 'G', 'G', 'W', 'G', 'G', 'G', 'G', 'G',
       'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G',
       'G', 'G', 'G', 'W', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'W', 'G',
       'G', 'W', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'W', 'G', 'G', 'G',
       'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'W', 'G', 'G', 'G',
       'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G',
       'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G',
       'G', 'G', 'G', 'G', 'G', 'G', 'G', 'W', 'G', 'G', 'W', 'G', 'G',
       'G', 'G', 'G', 'G', 'G', 'W', 'G', 'G', 'G', 'G', 'G', 'G', 'G',
       'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'W', 'G', 'G

In [11]:
#solving the inbalanced data using smote technique
smote=SMOTE(sampling_strategy='minority')
x_sm_1,y_sm_1 = smote.fit_resample(x_20,y_20)

In [12]:
#checking that the data is now balanced
unique, counts = np.unique(y_sm_1, return_counts=True)
dict(zip(unique, counts))

{'G': 465, 'W': 465}

In [13]:
#splitting data
X_train_20, X_test_20, Y_train_20, Y_test_20 = train_test_split(x_sm_1, y_sm_1, test_size = 0.25, random_state = 0)

In [14]:
#feature scaling
sc = StandardScaler()
X_train_20 = sc.fit_transform(X_train_20)
X_test_20 = sc.transform(X_test_20)

In [15]:
#svc model
# from sklearn.svm import SVC
# classifier = SVC(kernel = 'rbf', random_state = 0) 
# classifier.fit(X_train_20, Y_train_20) 

In [16]:
# fitting data into svc model using grid search
C_range = [0.25,0.5,1]
gamma_range = np.logspace(0.3,0.8)
param_grid = dict(gamma=gamma_range, C=C_range)
cv = 3

grid_20 = GridSearchCV(SVC(kernel = 'rbf', random_state = 0), param_grid=param_grid, cv=cv)
grid_20.fit(X_train_20,Y_train_20)

print(
    "The best parameters are %s with a score of %0.2f"
    % (grid_20.best_params_, grid_20.best_score_)
)

The best parameters are {'C': 1, 'gamma': 2.7080274434544167} with a score of 0.88


In [17]:
#predection at 20% of the data
Y_predict_20 = grid_20.predict(X_test_20)

In [18]:
Y_predict_20

array(['G', 'W', 'G', 'G', 'W', 'W', 'G', 'G', 'W', 'G', 'W', 'W', 'W',
       'G', 'G', 'W', 'W', 'W', 'G', 'W', 'W', 'W', 'W', 'W', 'W', 'G',
       'G', 'W', 'G', 'W', 'G', 'W', 'G', 'G', 'W', 'W', 'G', 'W', 'G',
       'G', 'G', 'W', 'W', 'W', 'G', 'G', 'W', 'W', 'G', 'W', 'W', 'W',
       'W', 'G', 'W', 'G', 'W', 'G', 'G', 'W', 'G', 'G', 'G', 'W', 'G',
       'G', 'G', 'W', 'W', 'G', 'W', 'W', 'W', 'W', 'W', 'G', 'G', 'W',
       'W', 'G', 'W', 'G', 'W', 'W', 'W', 'G', 'W', 'W', 'W', 'W', 'G',
       'W', 'G', 'W', 'G', 'G', 'W', 'W', 'W', 'G', 'W', 'G', 'W', 'W',
       'W', 'W', 'W', 'W', 'G', 'G', 'W', 'W', 'W', 'W', 'W', 'G', 'W',
       'G', 'G', 'W', 'W', 'G', 'W', 'W', 'G', 'G', 'G', 'G', 'W', 'W',
       'W', 'W', 'W', 'G', 'W', 'W', 'W', 'G', 'G', 'G', 'W', 'G', 'W',
       'G', 'W', 'G', 'G', 'W', 'G', 'W', 'G', 'W', 'G', 'W', 'W', 'G',
       'W', 'W', 'G', 'G', 'G', 'W', 'W', 'G', 'W', 'G', 'W', 'W', 'G',
       'G', 'W', 'G', 'G', 'W', 'W', 'G', 'W', 'W', 'G', 'W', 'W

In [19]:
# Displaying accuracy and confusion matrix (TP,FP,FN,TN)
con_matrx = confusion_matrix(Y_test_20, Y_predict_20)
print(con_matrx)
Accuracy=accuracy_score(Y_test_20, Y_predict_20) *100
print("Accuracy of this model at 20% is: " +str(Accuracy) + " %")

[[ 93  21]
 [ 11 108]]
Accuracy of this model at 20% is: 86.26609442060087 %


In [20]:
# X and Y at 50% of the data (quiz1,assignment1,midterm,assignemt2)
X_50=df.iloc[:, 0:4].values
Y_50=df.iloc[:, -1].values

In [21]:
X_50

array([[95, 91, 70, 90],
       [85, 76, 65, 61],
       [85, 41, 73, 61],
       ...,
       [80, 86, 93, 95],
       [75, 68, 80, 76],
       [85, 81, 88, 86]])

In [22]:
Y_50

array(['G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G',
       'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G',
       'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G',
       'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G',
       'G', 'G', 'G', 'G', 'G', 'G', 'G', 'W', 'G', 'G', 'G', 'G', 'G',
       'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G',
       'G', 'G', 'G', 'W', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'W', 'G',
       'G', 'W', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'W', 'G', 'G', 'G',
       'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'W', 'G', 'G', 'G',
       'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G',
       'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G',
       'G', 'G', 'G', 'G', 'G', 'G', 'G', 'W', 'G', 'G', 'W', 'G', 'G',
       'G', 'G', 'G', 'G', 'G', 'W', 'G', 'G', 'G', 'G', 'G', 'G', 'G',
       'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'W', 'G', 'G

In [23]:
smote=SMOTE(sampling_strategy='minority')
x_sm_2,y_sm_2 = smote.fit_resample(X_50,Y_50)

#x_sm.value_counts()

In [24]:
from sklearn.model_selection import train_test_split
X_train_50, X_test_50, Y_train_50, Y_test_50 = train_test_split(x_sm_2, y_sm_2, test_size = 0.25, random_state = 0)

In [25]:
#feature scaling
sc = StandardScaler()
X_train_50 = sc.fit_transform(X_train_50)
X_test_50 = sc.transform(X_test_50)

In [26]:
#svc model
# from sklearn.svm import SVC
# classifier = SVC(kernel = 'rbf', random_state = 0) 
# classifier.fit(X_train_50, Y_train_50) 

In [27]:
# fitting data into svc model using grid search
C_range = [0.25,0.5,1]
gamma_range = np.logspace(0.3,0.8)
param_grid = dict(gamma=gamma_range, C=C_range)
cv = 3

grid_50 = GridSearchCV(SVC(kernel = 'rbf', random_state = 0), param_grid=param_grid, cv=cv)
grid_50.fit(X_train_50,Y_train_50)

print(
    "The best parameters are %s with a score of %0.2f"
    % (grid_50.best_params_, grid_50.best_score_)
)

The best parameters are {'C': 1, 'gamma': 3.345721567317597} with a score of 0.97


In [28]:
Y_predict_50 = grid_50.predict(X_test_50)

In [29]:
Y_predict_50

array(['G', 'W', 'G', 'G', 'G', 'W', 'G', 'G', 'W', 'G', 'W', 'W', 'W',
       'G', 'G', 'W', 'W', 'W', 'G', 'W', 'W', 'W', 'G', 'W', 'W', 'G',
       'G', 'W', 'G', 'W', 'G', 'W', 'G', 'W', 'G', 'G', 'G', 'W', 'G',
       'G', 'G', 'W', 'W', 'W', 'G', 'G', 'W', 'W', 'G', 'W', 'W', 'W',
       'W', 'G', 'W', 'W', 'W', 'G', 'G', 'W', 'G', 'G', 'G', 'W', 'G',
       'G', 'G', 'W', 'W', 'G', 'W', 'W', 'W', 'W', 'G', 'G', 'W', 'W',
       'W', 'G', 'W', 'G', 'W', 'W', 'W', 'G', 'W', 'W', 'W', 'W', 'G',
       'G', 'G', 'G', 'G', 'G', 'W', 'W', 'W', 'G', 'W', 'G', 'W', 'W',
       'W', 'W', 'W', 'W', 'G', 'G', 'W', 'W', 'W', 'W', 'W', 'W', 'W',
       'G', 'G', 'W', 'W', 'G', 'W', 'W', 'G', 'W', 'G', 'G', 'W', 'W',
       'W', 'W', 'W', 'G', 'W', 'W', 'W', 'G', 'G', 'G', 'W', 'G', 'W',
       'G', 'W', 'G', 'G', 'G', 'G', 'W', 'G', 'G', 'W', 'W', 'W', 'G',
       'W', 'W', 'G', 'G', 'G', 'W', 'W', 'G', 'W', 'W', 'W', 'W', 'G',
       'G', 'W', 'G', 'G', 'W', 'W', 'G', 'W', 'W', 'G', 'W', 'W

In [30]:
# Displaying accuracy and confusion matrix (TP,FP,FN,TN)
con_matrx = confusion_matrix(Y_test_50, Y_predict_50)
print(con_matrx)
Accuracy=accuracy_score(Y_test_50, Y_predict_50) *100
print("Accuracy of this model at 50% is: " +str(Accuracy) + " %")

[[106   8]
 [  0 119]]
Accuracy of this model at 50% is: 96.56652360515021 %
